<a href="https://colab.research.google.com/github/Columbia-Neuropythonistas/PythonDataCourse2021/blob/main/Lecture0_Python%2BNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture0: Part 0 - "Pure" Python and Numpy

This notebook gives an introduction to "pure" Python, followed by Numpy

Note: in order to save a copy of this Google colab notebook to **your own** Google Drive, go to `File` > `Save a copy in Drive`

Please follow along with in your own notebook and play around with the code!

--> Course resources can be found here: www.neuropython.com

--> If you have questions during class or zoom breakout sessions, feel free to ask over **slack**


Outline for today's lecture:
* Go through Section 0 ("pure" python) with the entire class
* Split into Breakout Rooms for Section 1 (numpy)
* Zoom Break
* Do separate Colab notebook Lecture0:Part1-Matplotlib



-----

# Section 0: "Pure Python"

Let's start by assigning the variable `x` a value:

In [ ]:
x = 10

We can print `x` and see what it is:

In [ ]:
print(x)

10


Next we can create a **list** of 3 numbers:

In [ ]:
y = [1,2,3]

In [ ]:
print(y)

[1, 2, 3]


We can use the `type` function to determine what type of object x is:

In [ ]:
type(x)

int

This is short for integer.

Exercise: Use the `type` function on the object `10.3244`. 

Discussion: What type of object is it? How is it different from an `int`? What are thhe benefits of using `int`s?

In [ ]:
# Your code here



We can also see what type of object `y` is: it is a list!

In [ ]:
type(y)

list

For an `int` like `x`, we can do some basic math operations

In [ ]:
x*2

20

In [ ]:
x + 24

34

What happens if we try to do this with a list?

In [ ]:
y*2

[1, 2, 3, 1, 2, 3]

In [ ]:
y + y

[1, 2, 3, 1, 2, 3]

Discussion: This is strange...what is happening here?

## `for`, `while` and `if`

Let's creat a for loop that prints 10 numbers:

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


Discussion: Why does Python start counting from 0?

What's neat is that we can loop through objects in a list. Remember that `y` is a list:

In [ ]:
for i in y:
    print(i)

1
2
3


Exercise: Loop through the objects in the list `y` using a for loop, and print the **square** of each number.

Note that in Python, you can square a number using `**`, e.g. 10**2 = 100

In [ ]:
# Your code here



1
4
9


We can also use a `while` loop:

In [ ]:
n = 0
while n < 5:
    print(n)
    n = n +1
    

0
1
2
3
4


Discussion: When might you use a `while` loop instead of a `for` loop? What is a possible pitfall of a `while` loop?

## Strings

Now we can move on to strings! What exactly is a `string`?

In [ ]:
type('hi')

str

In [ ]:
type('10')

str

In [ ]:
type('the rain in spain')

str

Discussion: So...what defines a `string` in Python? Why is `'10'` a string?

In [ ]:
adjective = 'merry'
noun = 'lemming'

In [ ]:
phrase = adjective + noun

print(phrase)

merrylemming


In [ ]:
phrase = adjective + ' ' + noun

print(phrase)

merry lemming


In [ ]:
words = ['hi','bye','tie','fry']

Exercise: Create a `for` loop that selects the strings inside the above list, and prints each one

In [ ]:
# Your code here




Discussion: What is happening with the following `for` loop?

In [ ]:
for p in phrase:
    print(p)

m
e
r
r
y
 
l
e
m
m
i
n
g


## Booleans

In [ ]:
a = True
print(a)
b = False
print(b)

True
False


In [ ]:
type(a)

bool

In [ ]:
if a == True:
  print('this is True!')

this is True!


In [ ]:
if a:
  print('this is True!')

Discussion: What is the difference between these two cells (above)?

In [ ]:
if a == True:
    print('red')
elif b == True:
    print('blue')

red


In [ ]:
if a == True:
    print('red')
elif b == False:
    print('blue')

red


Discussion: We know that b is False. Why does the above code only print red?

Exercise: Write code that prints "red" if a is True, and also "blue if b is False

In [ ]:
# Your code here



Exercise: Write code that prints "red" if a is True AND  "blue if b is False in a single line of code (Hint: use `and`)

In [ ]:
# Your code here



Exercise: Use a `for` loop and an `if` statement to print the numbers 4,5,6,7 (there are many ways of doing this)

In [ ]:
# Your code here




`append` is one way of augmenting a list. Here is an example below:

In [ ]:
n = []
for i in range(4):
    n.append(i)

print(n)

[0, 1, 2, 3]


Exercise: Create an empty list, and append the following objects - a string, an int, a float, and a list. (No need to use a for loop). Note that a list can contain all sorts of objects simultaneously!

Discussion: What are the benefits of this? What are the pitfalls?

In [ ]:
# Your code here



How might we manipulate matrices? Or apply operations simultaneously to large sets of numbers? While "pure" Python gives us the necessary baseline for all Python code, we need to use libraries with extra functionality to do more complicated operations.

# Section 1: Starting with Numpy!

Work through the following code with your **zoom breakout room** group. One person should share their screen and read through the text outloud, while the rest guide them through the code.

Interactive learning can be really effective! If you are going to join a breakout room, please show your camera and contribute to the team effort.

`Numpy` is an external library, or package, that we can import using the following code:


In [ ]:
import numpy

It is standard practice to import `numpy` and relabel it `np` for short:

In [ ]:
import numpy as np

Discussion: Why would coders do this?

Numpy deals with "arrays." You can have 1-D arrays, 2-D arrays, or N-Dimensional arrays. You can think of these as vectors, matrices, and N-dimensional matrices if you like.

# 1-Dimensional Arrays

In [ ]:
a = [1,2,3,4] # this is a list
print('a: ',a)

b = np.array(a) # this is a numpy array
print('b: ',b)

a:  [1, 2, 3, 4]
b:  [1 2 3 4]


If we check the `type` of b, we see that it is an `numpy.ndarray` object 

In [ ]:
type(b)

numpy.ndarray

# Addition

We saw that we could add two lists, but that it essentially created a new list which was twice as long

In [ ]:
# adding two lists

[1,2,3,4] + [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

For most data analysis, we would want to be able to add two vectors or two matrices. Numpy arrays finally let us do this!

In [ ]:
# adding two numpy arrays
np.array([1,2,3,4]) + np.array([1,2,3,4])

array([2, 4, 6, 8])

Exercise: Create two numpy arrays of length 3 and subtract one from the other:

In [ ]:
# Your code here




Here is something slightly messy:

In [ ]:
# adding numpy array and a list
np.array([1,2,3,4]) + [1,2,3,4]

array([2, 4, 6, 8])

Discussion: What just happened here? What did Python just do? (Hint: it changed the `list` object to something else)

Exercise: Create a numpy array of length 3 and a list of length 2. Can you add them together? Why or why not?

In [ ]:
# Your code here



Exercise: Create a numpy array of length 3 and another numpy array of length 2. Can you add them together? Why or why not?


In [ ]:
# Your code here




# Multiplication

We saw before that we could mutliply a `list`...but it doesn't do what you would expect.

In [ ]:
# multiplying a list
[1,2,3,4] * 2

[1, 2, 3, 4, 1, 2, 3, 4]

Now, with numpy arrays, we can actually multiply each value inside the array:

In [ ]:
# multiplying an ndarray
np.array([1,2,3,4]) * 2

array([2, 4, 6, 8])

You cannot multiply two `list`s

In [ ]:
# multiplying two lists
[1,2,3,4] * [1,2,3,4]

TypeError: ignored

But you _can_ multiply two numpy arrays!

In [ ]:
# multiplying two numpy arrays - this is element-wise
np.array([1,2,3,4]) * np.array([1,2,3,4])

array([ 1,  4,  9, 16])

Exercise: Use a `for` loop to divide a numpy array with  values [2.1,4.33,5.62,8.999] by another numpy array of your choice 3 times (there are many ways to do this)

In [ ]:
# Your code here



# N-Dimensional Arrays

So far, we have only used 1-dimensional arrays (akin to vectors). We can start playing with 2-dimensional (i.e. matrices) or N-dimensional arrays:

In [ ]:
# 2 x 3 matrix
d1 = np.array([[1,2,3],[4,5,6]])
d1


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d1.shape

(2, 3)

In [ ]:
# another matrix
d2 = np.array([[1,2],[3,4],[5,6]])
d2

array([[1, 2],
       [3, 4],
       [5, 6]])

Exercise: Confirm that the shape of `d2` is (3,2) using `.shape`

In [ ]:
# Your code here



Exercise: Make sure you understand the code above. Create a 4 x4 array

In [ ]:
# Your code here



Exercise: Create a 1 x 2 x 3 array. Confirm that the shape is correct using `.shape`

In [ ]:
# Your code 



# Element-wise Multiplication

When working with matrices, the `*` operator applies element-wise multiplication. What does this mean exactly?

In [ ]:
# 2 x 3 matrix
d1 = np.array([[1,2,3],[4,5,6]])
d2 = np.array([[1,2],[3,4],[5,6]])

# element-wise multiplication
# (both matrices need to be the same shape)
d1*d1

array([[ 1,  4,  9],
       [16, 25, 36]])

Discussion: Explain what we just did

Exercise: Can you do element-wise multiplication if `d1` and `d2` have different shapes? Why or why not? Check with code below

In [ ]:
# Your code here



# Dot product

Discussion: Why can we take the dot product of matrices/arrays of different sizes?

In [ ]:
# dot product
d3 = np.dot(d1,d2)

d3

array([[22, 28],
       [49, 64]])

Another way to take the dot product is to use the `@` symbol

In [ ]:
d4 = d1 @ d2

d4

array([[22, 28],
       [49, 64]])

# Mathematical Functions

Exercise: Take the square of every element inside the numpy array `d3`

In [ ]:
# Your code here



Exercise: Take the square root of every element inside the numpy array `d3` using `np.sqrt()`

In [ ]:
# Your code here



Exercise: Take the exponential of every element inside the numpy array `d3` using `np.exp()`

In [ ]:
# Your code here



# `linspace` and `arange`

We often want to generate arrays automagically. `np.linspace()` and `np.arange()` are two ways of doing this

In [ ]:
x1 = np.linspace(0,1,10) # split into 10
x1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Discussion: What exactly is linspace doing?

Exercise: Use linspace to create the following array 
`array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])` (Hint - tweak the code from the line above)

In [ ]:
# Your code here

x1 = 
x1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

This is `np.arange()`

In [ ]:
x2 = np.arange(0,1,.1) # increase by 1
x2

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

Discussion: What exactly does `np.arange()` do?

Exercise: Use `np.arange()` to create an array of numbers from 50 to 100 with intervals of 5

In [ ]:
# Your code here



Exercise: Use `np.linspace()` to create an array of numbers from 50 to 100 with intervals of 5

In [ ]:
# Your code here



Here are a few other tips and tricks:

In [ ]:
z = np.ones(20) # create an array of ones!
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
z = np.zeros((5,2)) # create 2d array of zeros!
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# getting fancy

In [ ]:
x2 = np.arange(0,1,.1) # increase by 1

w = 1
y = np.sin(2*np.pi*w*x2)
y

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01])

Discussion: Describe each line of the code above.

# indexing

What if we want to select a single element from an np.array? Or a row of a matrix? Python allows us to do this seemlessly using indexing

In [ ]:
x = np.arange(10)

print('x: ',x)
x[2:5]

x:  [0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

Select the last two elements of the array `x`

In [ ]:
# Your code here



What if you don't know how long the array is? Python allows us to cleverly select the last two elements regardless of the array length

In [ ]:
x[-2:]

array([8, 9])

Exercise: What happens if we do `x[:-2` instead? Try it out below

In [ ]:
# Your code here



In [ ]:
x[1:7:2]

array([1, 3, 5])

Discussion: Explain what is happening in the above cell

Exercise: Create an array of numbers from 0 to 100 with an interval of 10. Using the slicing and indexing tricks above, print the numbers [20,40,60] (there are many ways to do this)

In [ ]:
# Your code here



In [ ]:
y = np.arange(35).reshape(5,7)
print('y: ',y)


y:  [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


Exercise: Using indexing in 2 dimensions, print out the following array:

array([ 0,  7, 14, 21, 28])

In [ ]:
# Your code here


array([ 0,  7, 14, 21, 28])

Exercise: Using indexing in 2 dimensions, print out the following array:

```py 
array([[ 7, 10, 13],
       [21, 24, 27]])
```

In [ ]:
# Your code here



# Index arrays


We can also use arrays to index arrays...pretty trippy

In [ ]:
x = np.arange(10,1,-1)
print('x: ',x)

x[np.array([3, 3, 1, 8])]



x:  [10  9  8  7  6  5  4  3  2]


array([7, 7, 9, 2])

Discussion: explain what is going on here

# Boolean or “mask” index arrays

We can also use Booleans to select elements from arrays

In [ ]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
b = y>20

print('b: ',b)

print('y[b]: ',y[b])

b:  [[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
y[b]:  [21 22 23 24 25 26 27 28 29 30 31 32 33 34]


Exercise: Create the following array from `y` above using a Boolean mask. (Hint: you can use reshape)

```py
array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])
```

In [ ]:
# Your code here



Well done! You are on your way to being a real pythonista. We can now move on to the next Colab notebook on **Matplotlib**

(see https://docs.scipy.org/doc/numpy/user/basics.indexing.html for more details on indexing)